FROM postgres:13

ENV POSTGRES_USER=default
ENV POSTGRES_PASSWORD=default
ENV POSTGRES_DB=NorthWind

COPY northwind.sql /docker-entrypoint-initdb.d/01-northwind.sql
COPY init_airflow_db.sql /docker-entrypoint-initdb.d/02-init_airflow_db.sql

RUN chmod a+r /docker-entrypoint-initdb.d/*