dwh_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: host.docker.internal
      port: 8123
      user: default
      password: default
      database: default