dwh_clickhouse:
  target: container
  outputs:
    local:
      type: clickhouse
      host: host.docker.internal
      port: 8123
      user: default
      password: default
      database: default
      schema: default
    container:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: default
      database: default
      schema: default